# Generated by Django 2.2.7 on 2019-11-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20191119_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(default="What's up?", max_length=200),
            preserve_default=False,
        ),
    ]
