# Generated by Django 2.2.7 on 2019-11-16 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20191116_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('course', models.CharField(max_length=50)),
                ('session_start', models.IntegerField()),
                ('session_end', models.IntegerField()),
                ('company', models.CharField(max_length=60)),
                ('job_profile', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('skills', models.TextField(max_length=100)),
                ('about_me', models.TextField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
